apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  labels:
    type: wordpress
spec:
  capacity:
    storage: {{ .Values.wordpress.persistence.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/wordpress"
  persistentVolumeReclaimPolicy: Retain
