apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: wordpress
  namespace: wordpress
spec:
  imageRepositoryRef:
    name: wordpress
  policy:
    semver:
      range: ">=1.0.0 <2.0.0"
