---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: wordpress
  namespace: wordpress
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: git-token
  url: ssh://git@github.com/AsmirIbr/k8s
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: wordpress
spec:
  interval: 1m
  chart:
    spec:
      chart: ./wordpress
      sourceRef:
        kind: GitRepository
        name: wordpress
      interval: 1m
  values:
    image:
      tag: "{{ .Values.wordpress.image.tag }}"
